## 전처리

### 데이터 불러오기

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

# Google Drive에 저장된 파일 경로 (필요에 따라 경로 수정)
critic_reviews_path = '/content/drive/MyDrive/기학팀플/rotten_tomatoes_critic_reviews.csv'
movies_path = '/content/drive/MyDrive/기학팀플/rotten_tomatoes_movies.csv'

# CSV 파일 읽기
critic_reviews = pd.read_csv(critic_reviews_path)
movies = pd.read_csv(movies_path)

### 데이터 확인

In [ ]:
# 데이터 확인
print("Critic Reviews 데이터 개요")
print(f"행 개수: {critic_reviews.shape[0]}, 열 개수: {critic_reviews.shape[1]}")
print("컬럼 이름:", list(critic_reviews.columns))
print("\n컬럼 타입:\n", critic_reviews.dtypes)

print("\nMovies 데이터 개요")
print(f"행 개수: {movies.shape[0]}, 열 개수: {movies.shape[1]}")
print("컬럼 이름:", list(movies.columns))
print("\n컬럼 타입:\n", movies.dtypes)

Critic Reviews 데이터 개요
행 개수: 1130017, 열 개수: 8
컬럼 이름: ['rotten_tomatoes_link', 'critic_name', 'top_critic', 'publisher_name', 'review_type', 'review_score', 'review_date', 'review_content']

컬럼 타입:
 rotten_tomatoes_link    object
critic_name             object
top_critic                bool
publisher_name          object
review_type             object
review_score            object
review_date             object
review_content          object
dtype: object

Movies 데이터 개요
행 개수: 17712, 열 개수: 22
컬럼 이름: ['rotten_tomatoes_link', 'movie_title', 'movie_info', 'critics_consensus', 'content_rating', 'genres', 'directors', 'authors', 'actors', 'original_release_date', 'streaming_release_date', 'runtime', 'production_company', 'tomatometer_status', 'tomatometer_rating', 'tomatometer_count', 'audience_status', 'audience_rating', 'audience_count', 'tomatometer_top_critics_count', 'tomatometer_fresh_critics_count', 'tomatometer_rotten_critics_count']

컬럼 타입:
 rotten_tomatoes_link                 object
movie_title                          object
movie_info                           object
critics_consensus                    object
content_rating                       object
genres                               object
directors                            object
authors                              object
actors                               object
original_release_date                object
streaming_release_date               object
runtime                             float64
production_company                   object
tomatometer_status                   object
tomatometer_rating                  float64
tomatometer_count                   float64
audience_status                      object
audience_rating                     float64
audience_count                      float64
tomatometer_top_critics_count         int64
tomatometer_fresh_critics_count       int64
tomatometer_rotten_critics_count      int64
dtype: object

### 합치기 위해 다른 형식 맞추기

In [ ]:
# 데이터 병합
merged_data = pd.merge(critic_reviews, movies, on='rotten_tomatoes_link', how='inner')

# 병합 결과 확인
print("병합된 데이터 개요")
print(f"행 개수: {merged_data.shape[0]}, 열 개수: {merged_data.shape[1]}")
print("컬럼 이름:", list(merged_data.columns))
print("\n컬럼 타입:\n", merged_data.dtypes)

병합된 데이터 개요
행 개수: 1129887, 열 개수: 29
컬럼 이름: ['rotten_tomatoes_link', 'critic_name', 'top_critic', 'publisher_name', 'review_type', 'review_score', 'review_date', 'review_content', 'movie_title', 'movie_info', 'critics_consensus', 'content_rating', 'genres', 'directors', 'authors', 'actors', 'original_release_date', 'streaming_release_date', 'runtime', 'production_company', 'tomatometer_status', 'tomatometer_rating', 'tomatometer_count', 'audience_status', 'audience_rating', 'audience_count', 'tomatometer_top_critics_count', 'tomatometer_fresh_critics_count', 'tomatometer_rotten_critics_count']

컬럼 타입:
 rotten_tomatoes_link                 object
critic_name                          object
top_critic                             bool
publisher_name                       object
review_type                          object
review_score                         object
review_date                          object
review_content                       object
movie_title                          object
movie_info                           object
critics_consensus                    object
content_rating                       object
genres                               object
directors                            object
authors                              object
actors                               object
original_release_date                object
streaming_release_date               object
runtime                             float64
production_company                   object
tomatometer_status                   object
tomatometer_rating                  float64
tomatometer_count                   float64
audience_status                      object
audience_rating                     float64
audience_count                      float64
tomatometer_top_critics_count         int64
tomatometer_fresh_critics_count       int64
tomatometer_rotten_critics_count      int64
dtype: object

In [ ]:
# 고유값 개수 확인
critic_reviews_unique = critic_reviews['rotten_tomatoes_link'].nunique()
movies_unique = movies['rotten_tomatoes_link'].nunique()
merged_unique = merged_data['rotten_tomatoes_link'].nunique()

print(f"Critic Reviews의 rotten_tomatoes_link 고유값 개수: {critic_reviews_unique}")
print(f"Movies의 rotten_tomatoes_link 고유값 개수: {movies_unique}")
print(f"병합된 데이터의 rotten_tomatoes_link 고유값 개수: {merged_unique}")

Critic Reviews의 rotten_tomatoes_link 고유값 개수: 17712
Movies의 rotten_tomatoes_link 고유값 개수: 17712
병합된 데이터의 rotten_tomatoes_link 고유값 개수: 17706

In [ ]:
# 병합되지 않은 링크 찾기
critic_links = set(critic_reviews['rotten_tomatoes_link'])
movie_links = set(movies['rotten_tomatoes_link'])

# 병합되지 않은 Critic Reviews 링크
missing_in_movies = critic_links - movie_links
print(f"Movies에 없는 Critic Reviews 링크 개수: {len(missing_in_movies)}")

# 병합되지 않은 Movies 링크
missing_in_critic = movie_links - critic_links
print(f"Critic Reviews에 없는 Movies 링크 개수: {len(missing_in_critic)}")

# 예시 확인
print("Movies에 없는 Critic Reviews 링크 일부:", list(missing_in_movies)[:6])
print("Critic Reviews에 없는 Movies 링크 일부:", list(missing_in_critic)[:6])

Movies에 없는 Critic Reviews 링크 개수: 6
Critic Reviews에 없는 Movies 링크 개수: 6
Movies에 없는 Critic Reviews 링크 일부: ['m/patton_oswalt_tragedy_+_comedy_equals_time', 'm/+_one_2019', 'm/-cule_valley_of_the_lost_ants', 'm/sympathy-for-the-devil-one-+-one', 'm/+h', 'm/-_man']
Critic Reviews에 없는 Movies 링크 일부: ['m/plus_one_2019', 'm/minus_man', 'm/minuscule_valley_of_the_lost_ants', 'm/sympathy-for-the-devil-one-plus-one', 'm/plush', 'm/patton_oswalt_tragedy_plus_comedy_equals_time']

In [ ]:
# '+'를 'plus'로, '-'를 'minus'로 통일
critic_reviews['rotten_tomatoes_link'] = critic_reviews['rotten_tomatoes_link'].str.replace(r'\+', 'plus', regex=True)
critic_reviews['rotten_tomatoes_link'] = critic_reviews['rotten_tomatoes_link'].str.replace(r'\-', 'minus', regex=True)

movies['rotten_tomatoes_link'] = movies['rotten_tomatoes_link'].str.replace(r'\+', 'plus', regex=True)
movies['rotten_tomatoes_link'] = movies['rotten_tomatoes_link'].str.replace(r'\-', 'minus', regex=True)

### 최종 합친 데이터 확인

In [ ]:
# 데이터 병합
merged_data = pd.merge(critic_reviews, movies, on='rotten_tomatoes_link', how='inner')

# 병합 결과 확인
print("병합된 데이터 개요")
print(f"행 개수: {merged_data.shape[0]}, 열 개수: {merged_data.shape[1]}")
print("컬럼 이름:", list(merged_data.columns))
print("\n컬럼 타입:\n", merged_data.dtypes)

병합된 데이터 개요
행 개수: 1130017, 열 개수: 29
컬럼 이름: ['rotten_tomatoes_link', 'critic_name', 'top_critic', 'publisher_name', 'review_type', 'review_score', 'review_date', 'review_content', 'movie_title', 'movie_info', 'critics_consensus', 'content_rating', 'genres', 'directors', 'authors', 'actors', 'original_release_date', 'streaming_release_date', 'runtime', 'production_company', 'tomatometer_status', 'tomatometer_rating', 'tomatometer_count', 'audience_status', 'audience_rating', 'audience_count', 'tomatometer_top_critics_count', 'tomatometer_fresh_critics_count', 'tomatometer_rotten_critics_count']

컬럼 타입:
 rotten_tomatoes_link                 object
critic_name                          object
top_critic                             bool
publisher_name                       object
review_type                          object
review_score                         object
review_date                          object
review_content                       object
movie_title                          object
movie_info                           object
critics_consensus                    object
content_rating                       object
genres                               object
directors                            object
authors                              object
actors                               object
original_release_date                object
streaming_release_date               object
runtime                             float64
production_company                   object
tomatometer_status                   object
tomatometer_rating                  float64
tomatometer_count                   float64
audience_status                      object
audience_rating                     float64
audience_count                      float64
tomatometer_top_critics_count         int64
tomatometer_fresh_critics_count       int64
tomatometer_rotten_critics_count      int64
dtype: object

### review score 형식 맞추기

In [ ]:
merged_data.head()

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content,movie_title,movie_info,...,production_company,tomatometer_status,tomatometer_rating,tomatometer_count,audience_status,audience_rating,audience_count,tomatometer_top_critics_count,tomatometer_fresh_critics_count,tomatometer_rotten_critics_count
0,m/0814255,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76
1,m/0814255,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff...",Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76
2,m/0814255,NaN,False,FILMINK (Australia),Fresh,NaN,2010-02-09,With a top-notch cast and dazzling special eff...,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76
3,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76
4,m/0814255,Ethan Alter,True,Hollywood Reporter,Rotten,NaN,2010-02-10,What's really lacking in The Lightning Thief i...,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...",...,20th Century Fox,Rotten,49.0,149.0,Spilled,53.0,254421.0,43,73,76

In [ ]:
import pandas as pd
from dateutil.parser import parse

# 1. 날짜 형식 여부를 확인하는 함수
def is_date(value):
    try:
        parse(value, fuzzy=False)
        return True
    except (ValueError, TypeError):
        return False

# 2. Letter Grade 점수 변환 함수
def convert_letter_grade(value):
    letter_grades = {
        "A+": 1, "A": 0.93, "A-": 0.84,
        "B+": 0.75, "B": 0.66, "B-": 0.57,
        "C+": 0.48, "C": 0.39, "C-": 0.30,
        "D+": 0.21, "D": 0.12, "D-": 0.03, "F": 0
    }
    return letter_grades.get(value, None)

# 3. 변환 로직 수정
def convert_review_score(value):
    if isinstance(value, str):
        value = value.strip()  # 공백 제거

        # '3.5/5' 형태 처리
        if "/" in value:
            try:
                num, denom = map(float, value.split("/"))

                # 분모가 0인 경우 처리
                if denom == 0:
                    denom = 10

                # 분자가 분모보다 크면 자릿수에 맞게 분모를 조정
                if num > denom:
                    num_digits = len(str(int(num)))  # 분자의 자릿수 계산
                    if num_digits == 1:
                        denom = 10
                    elif num_digits == 2:
                        denom = 100
                    elif num_digits == 3:
                        denom = 1000
                    else:
                        denom = 1000  # 그 이상의 자릿수는 1000으로 처리
                return num / denom
            except ValueError:
                return None

        # 날짜 형식 처리
        elif is_date(value):
            try:
                date_obj = parse(value)
                # MM/DD 형태로 변환하여 나누기
                return date_obj.month / date_obj.day
            except Exception as e:
                return None

        # Letter Grade 처리
        elif value in ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-","D+","D","D-","F"]:
            return convert_letter_grade(value)

        # 'C -'처럼 공백을 포함한 경우 처리
        elif " " in value:
            value = value.replace(" ", "")  # 공백 제거 후 다시 처리
            if value in ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-","D+","D","D-","F"]:
                return convert_letter_grade(value)

# 데이터 변환
merged_data['review_score_cleaned'] = merged_data['review_score'].apply(convert_review_score)

# 변환되지 않은 값 확인
unprocessed_scores = merged_data[merged_data['review_score_cleaned'].isnull() & merged_data['review_score'].notnull()]
print("변환되지 않은 값:", unprocessed_scores['review_score'].unique())

# 결과 확인
print(merged_data[['review_score', 'review_score_cleaned']].head())

변환되지 않은 값: ['0']
  review_score  review_score_cleaned
0          NaN                   NaN
1          NaN                   NaN
2          NaN                   NaN
3        3.5/5                   0.7
4          NaN                   NaN

In [ ]:
print(merged_data[['review_score', 'review_score_cleaned']].head(60))

   review_score  review_score_cleaned
0           NaN                   NaN
1           NaN                   NaN
2           NaN                   NaN
3         3.5/5                 0.700
4           NaN                   NaN
5           NaN                   NaN
6           1/4                 0.250
7         3.5/5                 0.700
8             B                 0.660
9           3/5                 0.600
10          4/5                 0.800
11          2/4                 0.500
12          2/5                 0.400
13          3/5                 0.600
14            C                 0.390
15        3.5/5                 0.700
16          NaN                   NaN
17        2.5/4                 0.625
18            B                 0.660
19          NaN                   NaN
20        2.5/4                 0.625
21          2/5                 0.400
22          1/4                 0.250
23          3/5                 0.600
24          2/5                 0.400
25          2/4                 0.500
26          3/5                 0.600
27          3/4                 0.750
28          NaN                   NaN
29          2/4                 0.500
30          2/4                 0.500
31          NaN                   NaN
32           C-                 0.300
33        2.5/4                 0.625
34       2.75/5                 0.550
35          3/5                 0.600
36        2.5/4                 0.625
37           B-                 0.570
38          2/4                 0.500
39          2/5                 0.400
40          3/4                 0.750
41          3/5                 0.600
42          NaN                   NaN
43          3/5                 0.600
44          NaN                   NaN
45        2.5/5                 0.500
46            C                 0.390
47          NaN                   NaN
48          1/4                 0.250
49          1/4                 0.250
50       5.5/10                 0.550
51          1/5                 0.200
52          2/4                 0.500
53          3/4                 0.750
54          2/4                 0.500
55           C+                 0.480
56        2.5/5                 0.500
57           D+                 0.210
58          2/5                 0.400
59          3/5                 0.600

In [ ]:
# 'review_score_cleaned'가 NaN이 아니고, 0 이상 1 이하인 값들의 개수 계산
valid_count = merged_data[(merged_data['review_score_cleaned'].notnull()) &
                          (merged_data['review_score_cleaned'] >= 0) &
                          (merged_data['review_score_cleaned'] <= 1)].shape[0]

# 유효한 값들의 비율 계산
valid_percentage = (valid_count / len(merged_data)) * 100

# 결과 출력
print(f"유효한 값 개수 (0 이상 1 이하, NaN 제외): {valid_count}")
print(f"유효한 값 비율 (0 이상 1 이하, NaN 제외): {valid_percentage:.2f}%")

유효한 값 개수 (0 이상 1 이하, NaN 제외): 822514
유효한 값 비율 (0 이상 1 이하, NaN 제외): 72.79%

In [ ]:
# 'review_score_cleaned'가 NaN이거나 0보다 작거나 1보다 큰 값인 행들을 삭제하고 merged_data에 할당
merged_data = merged_data[
    (merged_data['review_score_cleaned'].notnull()) &
    (merged_data['review_score_cleaned'] >= 0) &
    (merged_data['review_score_cleaned'] <= 1)
]

# 결과 확인
print(merged_data[['review_score', 'review_score_cleaned']].head(10))

   review_score  review_score_cleaned
3         3.5/5                  0.70
6           1/4                  0.25
7         3.5/5                  0.70
8             B                  0.66
9           3/5                  0.60
10          4/5                  0.80
11          2/4                  0.50
12          2/5                  0.40
13          3/5                  0.60
14            C                  0.39

### null 값 확인

In [ ]:
# 해당 컬럼들 제거
merged_data = merged_data.drop(columns=['rotten_tomatoes_link'])

In [ ]:
# 결측치 확인
print(merged_data.isnull().sum())

# 결측치 비율 확인
print(merged_data.isnull().mean() * 100)

critic_name                         14483
top_critic                              0
publisher_name                          0
review_type                             0
review_score                            0
review_date                             0
review_content                      65370
movie_title                             0
movie_info                           6092
critics_consensus                   97619
content_rating                          0
genres                                150
directors                           10358
authors                             38154
actors                               6884
original_release_date               14738
streaming_release_date               6665
runtime                              5233
production_company                   7504
tomatometer_status                   1002
tomatometer_rating                   1002
tomatometer_count                    1002
audience_status                     24691
audience_rating                      2605
audience_count                       2881
tomatometer_top_critics_count           0
tomatometer_fresh_critics_count         0
tomatometer_rotten_critics_count        0
review_score_cleaned                    0
dtype: int64
critic_name                          1.760821
top_critic                           0.000000
publisher_name                       0.000000
review_type                          0.000000
review_score                         0.000000
review_date                          0.000000
review_content                       7.947585
movie_title                          0.000000
movie_info                           0.740656
critics_consensus                   11.868369
content_rating                       0.000000
genres                               0.018237
directors                            1.259310
authors                              4.638705
actors                               0.836946
original_release_date                1.791824
streaming_release_date               0.810321
runtime                              0.636220
production_company                   0.912325
tomatometer_status                   0.121822
tomatometer_rating                   0.121822
tomatometer_count                    0.121822
audience_status                      3.001894
audience_rating                      0.316712
audience_count                       0.350268
tomatometer_top_critics_count        0.000000
tomatometer_fresh_critics_count      0.000000
tomatometer_rotten_critics_count     0.000000
review_score_cleaned                 0.000000
dtype: float64

In [ ]:
# review_content가 null인 행 제거
merged_data = merged_data.dropna(subset=['review_content'])

# 결과 출력 (확인용)
print(merged_data.head())

        critic_name  top_critic           publisher_name review_type  \
3      Ben McEachen       False  Sunday Mail (Australia)       Fresh
6      Nick Schager       False           Slant Magazine      Rotten
7  Bill Goodykoontz        True         Arizona Republic       Fresh
8    Jordan Hoffman       False                      UGO       Fresh
9      Jim Schembri        True      The Age (Australia)       Fresh

  review_score review_date                                     review_content  \
3        3.5/5  2010-02-09  Whether audiences will get behind The Lightnin...
6          1/4  2010-02-10  Harry Potter knockoffs don't come more transpa...
7        3.5/5  2010-02-10  Percy Jackson isn't a great movie, but it's a ...
8            B  2010-02-10                         Fun, brisk and imaginative
9          3/5  2010-02-10  Crammed with dragons, set-destroying fights an...

                                         movie_title  \
3  Percy Jackson & the Olympians: The Lightning T...
6  Percy Jackson & the Olympians: The Lightning T...
7  Percy Jackson & the Olympians: The Lightning T...
8  Percy Jackson & the Olympians: The Lightning T...
9  Percy Jackson & the Olympians: The Lightning T...

                                          movie_info  \
3  Always trouble-prone, the life of teenager Per...
6  Always trouble-prone, the life of teenager Per...
7  Always trouble-prone, the life of teenager Per...
8  Always trouble-prone, the life of teenager Per...
9  Always trouble-prone, the life of teenager Per...

                                   critics_consensus  ... tomatometer_status  \
3  Though it may seem like just another Harry Pot...  ...             Rotten
6  Though it may seem like just another Harry Pot...  ...             Rotten
7  Though it may seem like just another Harry Pot...  ...             Rotten
8  Though it may seem like just another Harry Pot...  ...             Rotten
9  Though it may seem like just another Harry Pot...  ...             Rotten

  tomatometer_rating tomatometer_count audience_status audience_rating  \
3               49.0             149.0         Spilled            53.0
6               49.0             149.0         Spilled            53.0
7               49.0             149.0         Spilled            53.0
8               49.0             149.0         Spilled            53.0
9               49.0             149.0         Spilled            53.0

  audience_count tomatometer_top_critics_count  \
3       254421.0                            43
6       254421.0                            43
7       254421.0                            43
8       254421.0                            43
9       254421.0                            43

   tomatometer_fresh_critics_count tomatometer_rotten_critics_count  \
3                               73                               76
6                               73                               76
7                               73                               76
8                               73                               76
9                               73                               76

  review_score_cleaned
3                 0.70
6                 0.25
7                 0.70
8                 0.66
9                 0.60

[5 rows x 29 columns]

### 날짜 형식 변환 및 중복값 확인

In [ ]:
# 1. 날짜 데이터 변환
merged_data['review_date'] = pd.to_datetime(merged_data['review_date'], errors='coerce')
merged_data['original_release_date'] = pd.to_datetime(merged_data['original_release_date'], errors='coerce')
merged_data['streaming_release_date'] = pd.to_datetime(merged_data['streaming_release_date'], errors='coerce')

In [ ]:

# 2. critic_name, review_date, movie_title 기준으로 중복된 데이터 확인 및 제거
merged_data = merged_data.drop_duplicates(subset=['critic_name', 'review_date', 'movie_title'])

# 결과 확인 (확인용)
print(merged_data[['critic_name', 'review_date', 'movie_title']].duplicated().sum())  # 중복된 데이터 수 출력
print(merged_data.head())  # 첫 5개 데이터 출력

0
        critic_name  top_critic           publisher_name review_type  \
3      Ben McEachen       False  Sunday Mail (Australia)       Fresh
6      Nick Schager       False           Slant Magazine      Rotten
7  Bill Goodykoontz        True         Arizona Republic       Fresh
8    Jordan Hoffman       False                      UGO       Fresh
9      Jim Schembri        True      The Age (Australia)       Fresh

  review_score review_date                                     review_content  \
3        3.5/5  2010-02-09  Whether audiences will get behind The Lightnin...
6          1/4  2010-02-10  Harry Potter knockoffs don't come more transpa...
7        3.5/5  2010-02-10  Percy Jackson isn't a great movie, but it's a ...
8            B  2010-02-10                         Fun, brisk and imaginative
9          3/5  2010-02-10  Crammed with dragons, set-destroying fights an...

                                         movie_title  \
3  Percy Jackson & the Olympians: The Lightning T...
6  Percy Jackson & the Olympians: The Lightning T...
7  Percy Jackson & the Olympians: The Lightning T...
8  Percy Jackson & the Olympians: The Lightning T...
9  Percy Jackson & the Olympians: The Lightning T...

                                          movie_info  \
3  Always trouble-prone, the life of teenager Per...
6  Always trouble-prone, the life of teenager Per...
7  Always trouble-prone, the life of teenager Per...
8  Always trouble-prone, the life of teenager Per...
9  Always trouble-prone, the life of teenager Per...

                                   critics_consensus  ... tomatometer_status  \
3  Though it may seem like just another Harry Pot...  ...             Rotten
6  Though it may seem like just another Harry Pot...  ...             Rotten
7  Though it may seem like just another Harry Pot...  ...             Rotten
8  Though it may seem like just another Harry Pot...  ...             Rotten
9  Though it may seem like just another Harry Pot...  ...             Rotten

  tomatometer_rating tomatometer_count audience_status audience_rating  \
3               49.0             149.0         Spilled            53.0
6               49.0             149.0         Spilled            53.0
7               49.0             149.0         Spilled            53.0
8               49.0             149.0         Spilled            53.0
9               49.0             149.0         Spilled            53.0

  audience_count tomatometer_top_critics_count  \
3       254421.0                            43
6       254421.0                            43
7       254421.0                            43
8       254421.0                            43
9       254421.0                            43

   tomatometer_fresh_critics_count tomatometer_rotten_critics_count  \
3                               73                               76
6                               73                               76
7                               73                               76
8                               73                               76
9                               73                               76

  review_score_cleaned
3                 0.70
6                 0.25
7                 0.70
8                 0.66
9                 0.60

[5 rows x 29 columns]

### 파일로

In [ ]:
# merged_data DataFrame을 'merged_data.csv' 파일로 저장
merged_data.to_csv('/content/drive/MyDrive/기학팀플/merged_data.csv', index=False)

### unique movie title

In [ ]:
# movie_title 컬럼에서 고유한 값들만 추출
unique_movie_titles = merged_data['movie_title'].unique()

# 새로운 DataFrame 생성, 컬럼 이름을 'movie_title'로 설정
new_df = pd.DataFrame(unique_movie_titles, columns=['movie_title'])

# 결과 확인
print(new_df)

                                             movie_title
0      Percy Jackson & the Olympians: The Lightning T...
1                                            Please Give
2                                                     10
3                        12 Angry Men (Twelve Angry Men)
4                           20,000 Leagues Under The Sea
...                                                  ...
17016                                          Zoot Suit
17017                                           Zootopia
17018                                    Zorba the Greek
17019                                               Zulu
17020                                          Zulu Dawn

[17021 rows x 1 columns]

In [ ]:
new_df.to_csv('/content/drive/MyDrive/기학팀플/movie_title.csv', index=False)

### 추가 전처리

In [ ]:
merged_data.dtypes

critic_name                                 object
top_critic                                    bool
publisher_name                              object
review_type                                 object
review_score                                object
review_date                         datetime64[ns]
review_content                              object
movie_title                                 object
movie_info                                  object
critics_consensus                           object
content_rating                              object
genres                                      object
directors                                   object
authors                                     object
actors                                      object
original_release_date               datetime64[ns]
streaming_release_date              datetime64[ns]
runtime                                    float64
production_company                          object
tomatometer_status                          object
tomatometer_rating                         float64
tomatometer_count                          float64
audience_status                             object
audience_rating                            float64
audience_count                             float64
tomatometer_top_critics_count                int64
tomatometer_fresh_critics_count              int64
tomatometer_rotten_critics_count             int64
review_score_cleaned                       float64
dtype: object

In [ ]:
# 원하는 컬럼 리스트
columns_to_keep = [
    'critic_name', 'top_critic', 'review_type','review_content', 'movie_title',
    'movie_info', 'content_rating', 'genres', 'directors', 'authors',
    'actors', 'original_release_date', 'runtime', 'production_company',
    'tomatometer_rating', 'tomatometer_count', 'audience_status','tomatometer_status',
    'audience_rating', 'audience_count', 'tomatometer_top_critics_count',
    'tomatometer_fresh_critics_count', 'tomatometer_rotten_critics_count',
    'review_score_cleaned'
]

# DataFrame에서 필요한 컬럼만 유지
filtered_df = merged_data[columns_to_keep]

# 결과 확인
print(filtered_df.head())

# 컬럼 타입 확인
print(filtered_df.dtypes)

        critic_name  top_critic review_type  \
3      Ben McEachen       False       Fresh
6      Nick Schager       False      Rotten
7  Bill Goodykoontz        True       Fresh
8    Jordan Hoffman       False       Fresh
9      Jim Schembri        True       Fresh

                                      review_content  \
3  Whether audiences will get behind The Lightnin...
6  Harry Potter knockoffs don't come more transpa...
7  Percy Jackson isn't a great movie, but it's a ...
8                         Fun, brisk and imaginative
9  Crammed with dragons, set-destroying fights an...

                                         movie_title  \
3  Percy Jackson & the Olympians: The Lightning T...
6  Percy Jackson & the Olympians: The Lightning T...
7  Percy Jackson & the Olympians: The Lightning T...
8  Percy Jackson & the Olympians: The Lightning T...
9  Percy Jackson & the Olympians: The Lightning T...

                                          movie_info content_rating  \
3  Always trouble-prone, the life of teenager Per...             PG
6  Always trouble-prone, the life of teenager Per...             PG
7  Always trouble-prone, the life of teenager Per...             PG
8  Always trouble-prone, the life of teenager Per...             PG
9  Always trouble-prone, the life of teenager Per...             PG

                                              genres       directors  \
3  Action & Adventure, Comedy, Drama, Science Fic...  Chris Columbus
6  Action & Adventure, Comedy, Drama, Science Fic...  Chris Columbus
7  Action & Adventure, Comedy, Drama, Science Fic...  Chris Columbus
8  Action & Adventure, Comedy, Drama, Science Fic...  Chris Columbus
9  Action & Adventure, Comedy, Drama, Science Fic...  Chris Columbus

                                      authors  ... tomatometer_rating  \
3  Craig Titley, Chris Columbus, Rick Riordan  ...               49.0
6  Craig Titley, Chris Columbus, Rick Riordan  ...               49.0
7  Craig Titley, Chris Columbus, Rick Riordan  ...               49.0
8  Craig Titley, Chris Columbus, Rick Riordan  ...               49.0
9  Craig Titley, Chris Columbus, Rick Riordan  ...               49.0

  tomatometer_count  audience_status tomatometer_status  audience_rating  \
3             149.0          Spilled             Rotten             53.0
6             149.0          Spilled             Rotten             53.0
7             149.0          Spilled             Rotten             53.0
8             149.0          Spilled             Rotten             53.0
9             149.0          Spilled             Rotten             53.0

   audience_count tomatometer_top_critics_count  \
3        254421.0                            43
6        254421.0                            43
7        254421.0                            43
8        254421.0                            43
9        254421.0                            43

  tomatometer_fresh_critics_count  tomatometer_rotten_critics_count  \
3                              73                                76
6                              73                                76
7                              73                                76
8                              73                                76
9                              73                                76

   review_score_cleaned
3                  0.70
6                  0.25
7                  0.70
8                  0.66
9                  0.60

[5 rows x 24 columns]
critic_name                                 object
top_critic                                    bool
review_type                                 object
review_content                              object
movie_title                                 object
movie_info                                  object
content_rating                              object
genres                                      object
directors                                   object
authors                                     object
actors                                      object
original_release_date               datetime64[ns]
runtime                                    float64
production_company                          object
tomatometer_rating                         float64
tomatometer_count                          float64
audience_status                             object
tomatometer_status                          object
audience_rating                            float64
audience_count                             float64
tomatometer_top_critics_count                int64
tomatometer_fresh_critics_count              int64
tomatometer_rotten_critics_count             int64
review_score_cleaned                       float64
dtype: object

In [ ]:
# top_critic 0,1로 변환
filtered_df['top_critic'] = filtered_df['top_critic'].astype(int)

<ipython-input-87-9be7e3f23eec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['top_critic'] = filtered_df['top_critic'].astype(int)

In [ ]:
# 각 컬럼의 고유값 출력
print("content_rating unique values:", filtered_df['content_rating'].unique())
print("audience_status unique values:", filtered_df['audience_status'].unique())

content_rating unique values: ['PG' 'R' 'NR' 'G' 'PG-13' 'NC17']
audience_status unique values: ['Spilled' 'Upright' nan]

In [ ]:
# Label Encoding for content_rating
filtered_df['content_rating_encoded'] = filtered_df['content_rating'].astype('category').cat.codes

# One-Hot Encoding for audience_status
audience_status_dummies = pd.get_dummies(filtered_df['audience_status'], prefix='audience_status')
filtered_df = pd.concat([filtered_df, audience_status_dummies], axis=1)

<ipython-input-89-af177d55512d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['content_rating_encoded'] = filtered_df['content_rating'].astype('category').cat.codes

In [ ]:
# audience_status_Spilled 0,1로 변환
filtered_df['audience_status_Spilled'] = filtered_df['audience_status_Spilled'].astype(int)

# audience_status_Upright 0,1로 변환
filtered_df['audience_status_Upright'] = filtered_df['audience_status_Upright'].astype(int)

In [ ]:
# genres 컬럼에서 공백 제거하고 소문자로 변환 후 고유값 추출
unique_genres = set()
filtered_df['genres'].dropna().apply(lambda x: unique_genres.update([genre.strip().lower() for genre in x.split(',')]))

# 고유한 장르 출력 및 개수
print("Unique genres:", unique_genres)
print("Number of unique genres:", len(unique_genres))

Unique genres: {'gay & lesbian', 'television', 'action & adventure', 'kids & family', 'horror', 'western', 'animation', 'mystery & suspense', 'special interest', 'faith & spirituality', 'science fiction & fantasy', 'sports & fitness', 'musical & performing arts', 'romance', 'comedy', 'cult movies', 'documentary', 'classics', 'art house & international', 'drama', 'anime & manga'}
Number of unique genres: 21

In [ ]:
# genres 컬럼에서 띄어쓰기를 제거하고 소문자로 변환
filtered_df['genres'] = filtered_df['genres'].str.replace(r'\s+', ' ', regex=True).str.strip().str.lower()

# 'anime & manga'를 'animation'으로 바꿔주기
filtered_df['genres'] = filtered_df['genres'].str.replace('anime & manga', 'animation', regex=False)

# genres 컬럼을 원핫 인코딩
genre_dummies = filtered_df['genres'].str.split(',', expand=True).stack().str.strip()

# 원핫 인코딩을 적용
genre_dummies = pd.get_dummies(genre_dummies, prefix='genre')

# 원핫 인코딩된 genre_dummies를 filtered_df에 추가
filtered_df = filtered_df.join(genre_dummies.groupby(level=0).sum())

In [ ]:
filtered_df = filtered_df.drop(columns=['genres','content_rating', 'audience_status'])

### 세션 계속 다운돼서 중간 저장

In [ ]:
filtered_df.to_csv('/content/drive/MyDrive/기학팀플/filtered_df.csv', index=False)

In [ ]:
import pandas as pd
filtered_df = pd.read_csv('/content/drive/MyDrive/기학팀플/filtered_df.csv')

### 이어서 전처리

In [ ]:
print(filtered_df.dtypes)

critic_name                          object
top_critic                            int64
review_type                          object
review_content                       object
movie_title                          object
movie_info                           object
directors                            object
authors                              object
actors                               object
original_release_date                object
runtime                             float64
production_company                   object
tomatometer_rating                  float64
tomatometer_count                   float64
tomatometer_status                   object
audience_rating                     float64
audience_count                      float64
tomatometer_top_critics_count         int64
tomatometer_fresh_critics_count       int64
tomatometer_rotten_critics_count      int64
review_score_cleaned                float64
content_rating_encoded                int64
audience_status_Spilled               int64
audience_status_Upright               int64
genre_action & adventure            float64
genre_animation                     float64
genre_art house & international     float64
genre_classics                      float64
genre_comedy                        float64
genre_cult movies                   float64
genre_documentary                   float64
genre_drama                         float64
genre_faith & spirituality          float64
genre_gay & lesbian                 float64
genre_horror                        float64
genre_kids & family                 float64
genre_musical & performing arts     float64
genre_mystery & suspense            float64
genre_romance                       float64
genre_science fiction & fantasy     float64
genre_special interest              float64
genre_sports & fitness              float64
genre_television                    float64
genre_western                       float64
dtype: object

In [ ]:
print(filtered_df.head())

        critic_name  top_critic review_type  \
0      Ben McEachen           0       Fresh
1      Nick Schager           0      Rotten
2  Bill Goodykoontz           1       Fresh
3    Jordan Hoffman           0       Fresh
4      Jim Schembri           1       Fresh

                                      review_content  \
0  Whether audiences will get behind The Lightnin...
1  Harry Potter knockoffs don't come more transpa...
2  Percy Jackson isn't a great movie, but it's a ...
3                         Fun, brisk and imaginative
4  Crammed with dragons, set-destroying fights an...

                                         movie_title  \
0  Percy Jackson & the Olympians: The Lightning T...
1  Percy Jackson & the Olympians: The Lightning T...
2  Percy Jackson & the Olympians: The Lightning T...
3  Percy Jackson & the Olympians: The Lightning T...
4  Percy Jackson & the Olympians: The Lightning T...

                                          movie_info       directors  \
0  Always trouble-prone, the life of teenager Per...  Chris Columbus
1  Always trouble-prone, the life of teenager Per...  Chris Columbus
2  Always trouble-prone, the life of teenager Per...  Chris Columbus
3  Always trouble-prone, the life of teenager Per...  Chris Columbus
4  Always trouble-prone, the life of teenager Per...  Chris Columbus

                                      authors  \
0  Craig Titley, Chris Columbus, Rick Riordan
1  Craig Titley, Chris Columbus, Rick Riordan
2  Craig Titley, Chris Columbus, Rick Riordan
3  Craig Titley, Chris Columbus, Rick Riordan
4  Craig Titley, Chris Columbus, Rick Riordan

                                              actors original_release_date  \
0  Logan Lerman, Brandon T. Jackson, Alexandra Da...            2010-02-12
1  Logan Lerman, Brandon T. Jackson, Alexandra Da...            2010-02-12
2  Logan Lerman, Brandon T. Jackson, Alexandra Da...            2010-02-12
3  Logan Lerman, Brandon T. Jackson, Alexandra Da...            2010-02-12
4  Logan Lerman, Brandon T. Jackson, Alexandra Da...            2010-02-12

   ...  genre_horror genre_kids & family  genre_musical & performing arts  \
0  ...           0.0                 0.0                              0.0
1  ...           0.0                 0.0                              0.0
2  ...           0.0                 0.0                              0.0
3  ...           0.0                 0.0                              0.0
4  ...           0.0                 0.0                              0.0

   genre_mystery & suspense genre_romance  genre_science fiction & fantasy  \
0                       0.0           0.0                              1.0
1                       0.0           0.0                              1.0
2                       0.0           0.0                              1.0
3                       0.0           0.0                              1.0
4                       0.0           0.0                              1.0

   genre_special interest  genre_sports & fitness  genre_television  \
0                     0.0                     0.0               0.0
1                     0.0                     0.0               0.0
2                     0.0                     0.0               0.0
3                     0.0                     0.0               0.0
4                     0.0                     0.0               0.0

   genre_western
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0

[5 rows x 44 columns]

In [ ]:
import pandas as pd

# 'production_company'의 고유값과 빈도수를 계산
production_company_counts = filtered_df['production_company'].value_counts()

# 고유값별로 카운트한 후, 상위 500개씩 범주 나누기
num_categories = 6
category_size = 500

# 빈도수가 높은 순으로 정렬된 고유값 리스트
sorted_companies = production_company_counts.index.tolist()

# 각 범주에 해당하는 고유값을 나누어 저장
categories = {i: [] for i in range(1, num_categories+1)}
remaining = []  # 6번 카테고리에 들어갈 나머지 값들

# 고유값을 500개씩 나누기
for i, company in enumerate(sorted_companies):
    category_num = (i // category_size) + 1
    if category_num <= num_categories:
        categories[category_num].append(company)
    else:
        remaining.append(company)

# 나머지 값들은 6번 카테고리에 넣기
categories[6].extend(remaining)

# 결과 출력
for category, companies in categories.items():
    print(f"Category {category}: {len(companies)} companies")

# 만약 각 범주에 속하는 'production_company' 값을 새 컬럼으로 추가하고 싶다면
def assign_category(company):
    for category, companies in categories.items():
        if company in companies:
            return category
    return 6  # default case (shouldn't happen)

filtered_df['production_company_category'] = filtered_df['production_company'].apply(assign_category)

# 확인
filtered_df[['production_company', 'production_company_category']].head()

Category 1: 500 companies
Category 2: 500 companies
Category 3: 500 companies
Category 4: 500 companies
Category 5: 500 companies
Category 6: 531 companies

  production_company  production_company_category
0   20th Century Fox                            1
1   20th Century Fox                            1
2   20th Century Fox                            1
3   20th Century Fox                            1
4   20th Century Fox                            1

In [ ]:
# 'directors'의 고유값별 빈도수 계산 (빈도수가 많은 순서대로 정렬)
directors_counts = filtered_df['directors'].value_counts()

# 빈도수를 기준으로 감독들을 내림차순 정렬
directors_sorted = directors_counts.sort_values(ascending=False)

# 감독 순서대로 상위 500명, 1500명, 4000명, 6500명까지 각 범주로 나누기
directors_sorted = directors_sorted.reset_index()
directors_sorted.columns = ['director', 'count']

# 각 범주에 맞는 상위 n명을 분배
category_bins = [500, 1500, 4000, 6500]
category_labels = ['1', '2', '3', '4', '5']

# 감독들의 순위별로 범주를 할당
directors_sorted['category'] = pd.cut(directors_sorted.index, bins=[0] + category_bins + [directors_sorted.shape[0]], labels=category_labels)

# 이제, directors_sorted에 있는 category를 filtered_df에 매핑
# filtered_df['directors'] 열에 대한 카테고리를 추가
directors_dict = dict(zip(directors_sorted['director'], directors_sorted['category']))
filtered_df['directors_category'] = filtered_df['directors'].map(directors_dict)

# NaN 값을 0으로 채우고 int로 변환
filtered_df['directors_category'] = filtered_df['directors_category'].fillna(0).astype(int)

# 결과 확인
print(filtered_df[['directors', 'directors_category']].head())

        directors  directors_category
0  Chris Columbus                   1
1  Chris Columbus                   1
2  Chris Columbus                   1
3  Chris Columbus                   1
4  Chris Columbus                   1

In [ ]:
filtered_df = filtered_df.drop(columns=['production_company','directors'])

In [ ]:
filtered_df.dtypes

critic_name                          object
top_critic                            int64
review_type                          object
review_content                       object
movie_title                          object
movie_info                           object
authors                              object
actors                               object
original_release_date                object
runtime                             float64
tomatometer_rating                  float64
tomatometer_count                   float64
tomatometer_status                   object
audience_rating                     float64
audience_count                      float64
tomatometer_top_critics_count         int64
tomatometer_fresh_critics_count       int64
tomatometer_rotten_critics_count      int64
review_score_cleaned                float64
content_rating_encoded                int64
audience_status_Spilled               int64
audience_status_Upright               int64
genre_action & adventure            float64
genre_animation                     float64
genre_art house & international     float64
genre_classics                      float64
genre_comedy                        float64
genre_cult movies                   float64
genre_documentary                   float64
genre_drama                         float64
genre_faith & spirituality          float64
genre_gay & lesbian                 float64
genre_horror                        float64
genre_kids & family                 float64
genre_musical & performing arts     float64
genre_mystery & suspense            float64
genre_romance                       float64
genre_science fiction & fantasy     float64
genre_special interest              float64
genre_sports & fitness              float64
genre_television                    float64
genre_western                       float64
production_company_category           int64
directors_category                    int64
dtype: object

### 추가 전처리

In [ ]:
# 'review_type'의 유니크한 값 출력
review_type_unique = filtered_df['review_type'].unique()
print("review_type의 유니크한 값:", review_type_unique)

# 'tomatometer_status'의 유니크한 값 출력
tomatometer_status_unique = filtered_df['tomatometer_status'].unique()
print("tomatometer_status의 유니크한 값:", tomatometer_status_unique)

review_type의 유니크한 값: ['Fresh' 'Rotten']
tomatometer_status의 유니크한 값: ['Rotten' 'Certified-Fresh' 'Fresh' nan]

In [ ]:
# 'review_type' 변환: 'Fresh' -> 1, 'Rotten' -> 0
filtered_df['review_type'] = filtered_df['review_type'].map({'Fresh': 1, 'Rotten': 0})

# 'tomatometer_status' 변환: 'Certified-Fresh' -> 1, 'Fresh' -> 1, 'Rotten' -> 0, NaN은 그대로 유지
filtered_df['tomatometer_status'] = filtered_df['tomatometer_status'].map({
    'Certified-Fresh': 1, 'Fresh': 1, 'Rotten': 0
})

In [ ]:
# 'tomatometer_rating'과 'audience_rating'의 값 범위 확인
tomatometer_rating_range = filtered_df['tomatometer_rating'].min(), filtered_df['tomatometer_rating'].max()
audience_rating_range = filtered_df['audience_rating'].min(), filtered_df['audience_rating'].max()

print("tomatometer_rating의 범위:", tomatometer_rating_range)
print("audience_rating의 범위:", audience_rating_range)

tomatometer_rating의 범위: (0.0, 100.0)
audience_rating의 범위: (0.0, 100.0)

In [ ]:
# 'tomatometer_rating'과 'audience_rating' 값을 0과 1 사이로 변환
filtered_df['tomatometer_rating'] = filtered_df['tomatometer_rating'] / 100
filtered_df['audience_rating'] = filtered_df['audience_rating'] / 100

# 변환된 결과 확인
print(filtered_df[['tomatometer_rating', 'audience_rating']].head(10))

   tomatometer_rating  audience_rating
0                0.49             0.53
1                0.49             0.53
2                0.49             0.53
3                0.49             0.53
4                0.49             0.53
5                0.49             0.53
6                0.49             0.53
7                0.49             0.53
8                0.49             0.53
9                0.49             0.53

### movie_info 텍스트 분석

In [ ]:
filtered_df['movie_info']

0         Always trouble-prone, the life of teenager Per...
1         Always trouble-prone, the life of teenager Per...
2         Always trouble-prone, the life of teenager Per...
3         Always trouble-prone, the life of teenager Per...
4         Always trouble-prone, the life of teenager Per...
                                ...
676576    In 1879, the Zulu nation hands colonial Britis...
676577    Sir Henry Bartle Frere's (John Mills) vastly o...
676578    Sir Henry Bartle Frere's (John Mills) vastly o...
676579    Sir Henry Bartle Frere's (John Mills) vastly o...
676580    Sir Henry Bartle Frere's (John Mills) vastly o...
Name: movie_info, Length: 676581, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# NaN 값 처리 (빈 문자열로 대체)
filtered_df['movie_info'] = filtered_df['movie_info'].fillna('')

# TF-IDF 벡터화
vectorizer = TfidfVectorizer(stop_words='english', max_features=50)  # 50개 단어를 추출
X = vectorizer.fit_transform(filtered_df['movie_info'])

# 각 문서에서 가장 중요한 키워드 5개 추출
important_keywords = vectorizer.get_feature_names_out()

# TF-IDF 값으로 가장 중요한 키워드 5개를 뽑아서 'movie_info_keyword' 컬럼에 저장
def get_top_keywords(tfidf_vector, top_n=5):
    # TF-IDF 값이 높은 상위 N개 단어 인덱스를 추출
    top_indices = np.argsort(tfidf_vector.toarray()).flatten()[-top_n:]
    top_keywords = important_keywords[top_indices]
    return ' '.join(top_keywords)

# 각 영화의 줄거리에서 상위 5개 키워드를 추출하여 'movie_info_keyword' 컬럼에 저장
filtered_df['movie_info_keyword'] = [get_top_keywords(X[i]) for i in range(X.shape[0])]

# 결과 확인
print(filtered_df[['movie_info', 'movie_info_keyword']].head())

                                          movie_info        movie_info_keyword
0  Always trouble-prone, the life of teenager Per...  life war mother son gets
1  Always trouble-prone, the life of teenager Per...  life war mother son gets
2  Always trouble-prone, the life of teenager Per...  life war mother son gets
3  Always trouble-prone, the life of teenager Per...  life war mother son gets
4  Always trouble-prone, the life of teenager Per...  life war mother son gets

In [ ]:
filtered_df.head()

,critic_name,top_critic,review_type,review_content,movie_title,movie_info,authors,actors,original_release_date,runtime,...,genre_mystery & suspense,genre_romance,genre_science fiction & fantasy,genre_special interest,genre_sports & fitness,genre_television,genre_western,production_company_category,directors_category,movie_info_keyword
0,Ben McEachen,0,1,Whether audiences will get behind The Lightnin...,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...","Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets
1,Nick Schager,0,0,Harry Potter knockoffs don't come more transpa...,Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...","Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets
2,Bill Goodykoontz,1,1,"Percy Jackson isn't a great movie, but it's a ...",Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...","Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets
3,Jordan Hoffman,0,1,"Fun, brisk and imaginative",Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...","Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets
4,Jim Schembri,1,1,"Crammed with dragons, set-destroying fights an...",Percy Jackson & the Olympians: The Lightning T...,"Always trouble-prone, the life of teenager Per...","Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets

In [ ]:
import pandas as pd

# original_release_date 컬럼을 datetime 형식으로 변환
filtered_df['original_release_date'] = pd.to_datetime(filtered_df['original_release_date'], errors='coerce')

# 변환 결과 확인
print(filtered_df.dtypes)  # datetime으로 변환되었는지 확인

critic_name                                 object
top_critic                                   int64
review_type                                  int64
review_content                              object
movie_title                                 object
movie_info                                  object
authors                                     object
actors                                      object
original_release_date               datetime64[ns]
runtime                                    float64
tomatometer_rating                         float64
tomatometer_count                          float64
tomatometer_status                         float64
audience_rating                            float64
audience_count                             float64
tomatometer_top_critics_count                int64
tomatometer_fresh_critics_count              int64
tomatometer_rotten_critics_count             int64
review_score_cleaned                       float64
content_rating_encoded                       int64
audience_status_Spilled                      int64
audience_status_Upright                      int64
genre_action & adventure                   float64
genre_animation                            float64
genre_art house & international            float64
genre_classics                             float64
genre_comedy                               float64
genre_cult movies                          float64
genre_documentary                          float64
genre_drama                                float64
genre_faith & spirituality                 float64
genre_gay & lesbian                        float64
genre_horror                               float64
genre_kids & family                        float64
genre_musical & performing arts            float64
genre_mystery & suspense                   float64
genre_romance                              float64
genre_science fiction & fantasy            float64
genre_special interest                     float64
genre_sports & fitness                     float64
genre_television                           float64
genre_western                              float64
production_company_category                  int64
directors_category                           int64
movie_info_keyword                          object
dtype: object

In [ ]:
# movie_info 열 제거
filtered_df = filtered_df.drop(columns=['movie_info'])

# 변경된 데이터프레임 확인
filtered_df

,critic_name,top_critic,review_type,review_content,movie_title,authors,actors,original_release_date,runtime,tomatometer_rating,...,genre_mystery & suspense,genre_romance,genre_science fiction & fantasy,genre_special interest,genre_sports & fitness,genre_television,genre_western,production_company_category,directors_category,movie_info_keyword
0,Ben McEachen,0,1,Whether audiences will get behind The Lightnin...,Percy Jackson & the Olympians: The Lightning T...,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,0.49,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets
1,Nick Schager,0,0,Harry Potter knockoffs don't come more transpa...,Percy Jackson & the Olympians: The Lightning T...,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,0.49,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets
2,Bill Goodykoontz,1,1,"Percy Jackson isn't a great movie, but it's a ...",Percy Jackson & the Olympians: The Lightning T...,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,0.49,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets
3,Jordan Hoffman,0,1,"Fun, brisk and imaginative",Percy Jackson & the Olympians: The Lightning T...,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,0.49,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets
4,Jim Schembri,1,1,"Crammed with dragons, set-destroying fights an...",Percy Jackson & the Olympians: The Lightning T...,"Craig Titley, Chris Columbus, Rick Riordan","Logan Lerman, Brandon T. Jackson, Alexandra Da...",2010-02-12,119.0,0.49,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,1,life war mother son gets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676576,NaN,0,1,"This is that rarity in films - an all-action, ...",Zulu,"Cy Endfield, John Prebble","Stanley Baker, Jack Hawkins, Ulla Jacobsson, J...",1964-06-17,135.0,0.96,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,4,help takes john daughter michael
676577,Ken Hanke,0,1,"Seen today, it's not only a startling indictme...",Zulu Dawn,"Cy Endfield, Anthony Storey","Burt Lancaster, Peter O'Toole, Simon Ward, Joh...",1979-12-14,121.0,0.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6,4,love make help young john
676578,Dennis Schwartz,0,1,A rousing visual spectacle that's a prequel of...,Zulu Dawn,"Cy Endfield, Anthony Storey","Burt Lancaster, Peter O'Toole, Simon Ward, Joh...",1979-12-14,121.0,0.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6,4,love make help young john
676579,Christopher Lloyd,0,0,"A simple two-act story: Prelude to war, and th...",Zulu Dawn,"Cy Endfield, Anthony Storey","Burt Lancaster, Peter O'Toole, Simon Ward, Joh...",1979-12-14,121.0,0.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6,4,love make help young john
676580,Brent McKnight,0,0,Rides the line between being a pure artifact o...,Zulu Dawn,"Cy Endfield, Anthony Storey","Burt Lancaster, Peter O'Toole, Simon Ward, Joh...",1979-12-14,121.0,0.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6,4,love make help young john

In [ ]:
filtered_df.to_csv('/content/drive/MyDrive/기학팀플/filtered_df_plus_info.csv', index=False)

In [ ]:
filtered_df.dtypes

critic_name                                 object
top_critic                                   int64
review_type                                  int64
review_content                              object
movie_title                                 object
authors                                     object
actors                                      object
original_release_date               datetime64[ns]
runtime                                    float64
tomatometer_rating                         float64
tomatometer_count                          float64
tomatometer_status                         float64
audience_rating                            float64
audience_count                             float64
tomatometer_top_critics_count                int64
tomatometer_fresh_critics_count              int64
tomatometer_rotten_critics_count             int64
review_score_cleaned                       float64
content_rating_encoded                       int64
audience_status_Spilled                      int64
audience_status_Upright                      int64
genre_action & adventure                   float64
genre_animation                            float64
genre_art house & international            float64
genre_classics                             float64
genre_comedy                               float64
genre_cult movies                          float64
genre_documentary                          float64
genre_drama                                float64
genre_faith & spirituality                 float64
genre_gay & lesbian                        float64
genre_horror                               float64
genre_kids & family                        float64
genre_musical & performing arts            float64
genre_mystery & suspense                   float64
genre_romance                              float64
genre_science fiction & fantasy            float64
genre_special interest                     float64
genre_sports & fitness                     float64
genre_television                           float64
genre_western                              float64
production_company_category                  int64
directors_category                           int64
movie_info_keyword                          object
dtype: object